_schema: _schema
paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: src/pages
    glob: []
    name: Pages
    icon: pages
    url: '[relative_base_path]/[slug]/'
    disable_url: false
    description: ''
    _enabled_editors:
      - visual
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
  posts:
    path: src/content/post
    glob:
      - '*.md'
      - '*.mdx'
    name: Posts
    icon: event_available
    url: /[slug]/
    disable_url: false
    description: ''
    _enabled_editors:
      - content
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
